# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          ENVIRONMENT: DEV
          RESULTS_FOLDER: reports

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install --upgrade pip
      # Step 3: run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest test/api --alluredir $RESULTS_FOLDER
            allure serve $RESULTS_FOLDER